name         'jeekl-weechat'
version      '0.1.0'
author       'jeekl <jeff.eklund@gmail.com>'
license      'MIT'
summary      'Installs the irc client Weechat'
project_page 'https://github.com/jeekl/puppet-weechat'
